site_name: directed_howis-ingestor
site_description: A simple HOWIS data ingestor
site_author: Henning Bredel

repo_url: https://github.com/ridoo/https://github.com/52North/directed_howis-ingestor
edit_uri: https://github.com/ridoo/https://github.com/52North/directed_howis-ingestor/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
